package views;

import classes.Database;

//import classes.Person;
import javax.swing.JOptionPane;
//import hospital.control.HospitalControl;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author isaac
 */
public class Login extends javax.swing.JFrame {

    String name, id, surname, address, username, phone;
    int age = 0;
    String pass = "";
    Database data = new Database();

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        jLabelFondoLoggin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/usuario.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 200, 130));

        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contraseña: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuario: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("Iniciar sesión");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 170, 40));

        checkIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkIn.setText("Registrarse");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });
        getContentPane().add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 160, 40));

        jLabelFondoLoggin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/halo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        //String aux = new String (pass);

        switch (data.validateUser(userTxt.getText(), passwordText.getText())) {

            case 1:
                JOptionPane.showMessageDialog(null, "Bienvenido Administrador...");
                Navigation NavigationWindow;
                NavigationWindow = new Navigation();
                NavigationWindow.show();
                this.dispose();
                break;

            case 2:
                JOptionPane.showMessageDialog(null, "Bienvenido Supervisor...");
                Users employeeWindow;
                employeeWindow = new Users();
                employeeWindow.show();
                this.dispose();
                break;

            case 3:
                JOptionPane.showMessageDialog(null, "Bienvenido Secretari@...");
                Users secretaryWindow;
                secretaryWindow = new Users();
                secretaryWindow.show();
                this.dispose();
                break;

            default:
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                break;

        }
    }//GEN-LAST:event_loginActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed

        //outputFile = new DataOutputStream(new FileOutputStream("data.txt", true));
        //inputFile = new DataInputStream(new FileInputStream("data.txt"));
        Users window = new Users();
        window.show();
        this.dispose();

    }//GEN-LAST:event_checkInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondoLoggin;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
