package views;

import classes.Database;
import classes.Service;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author isaac
 */
public class MedicalHistory extends javax.swing.JFrame {

    /**
     * Creates new form MedicalHistory
     */
    String uType;
    Database d;
    DefaultTableModel tb;
    ArrayList<Service> services;

    public MedicalHistory(String userType) {
        initComponents();
        uType = userType;
        d = new Database();
        String header[] = {"ID", "Tipo", "Cliente", "Precio", "Descripción"};
        String data[][] = {};
        tb = new DefaultTableModel(data, header);
        servicesTable.setModel(tb);
        this.setLocationRelativeTo(null);
        services = d.getServices();
        displayServices();
        hideSearch();
    }

    public MedicalHistory() {
        initComponents();
        uType = "";
        d = new Database();
        d = new Database();
        String header[] = {"ID", "Tipo", "Cliente", "Precio", "Descripción"};
        String data[][] = {};
        tb = new DefaultTableModel(data, header);
        servicesTable.setModel(tb);
        this.setLocationRelativeTo(null);
        services = d.getServices();
        displayServices();
    }

    public void fillRow(Service s) {
        int id = s.getId();
        int price = s.getPrice();
        String type = s.getType();
        String client = s.getClientName();
        String description = s.getDescription();
        String data[] = {String.valueOf(id), type,
            client, String.valueOf(price), description};

        tb.addRow(data);
    }

    public void displayServices() {
        tb.setRowCount(0);
        for (Service s : services) {
            fillRow(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MHLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        servicesSP = new javax.swing.JScrollPane();
        servicesTable = new javax.swing.JTable();
        displayComboBox = new javax.swing.JComboBox<>();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        bgdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MHLabel.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        MHLabel.setForeground(new java.awt.Color(255, 255, 255));
        MHLabel.setText("Historial Médico");
        jPanel1.add(MHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 40));

        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 740, 4));

        servicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", " Servicio", "Cliente", "Precio", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        servicesSP.setViewportView(servicesTable);

        jPanel1.add(servicesSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 750, 330));

        displayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Búsqueda Personalizada" }));
        displayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(displayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));
        jPanel1.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 280, 30));

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 80, 30));

        backButton.setText("Regresar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 30, 90, 30));

        bgdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/shrek (1).jpg"))); // NOI18N
        bgdLabel.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(bgdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void displayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayComboBoxActionPerformed
    }//GEN-LAST:event_displayComboBoxActionPerformed
*/
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        Navigation nav = new Navigation(uType);
        nav.show();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        tb.setRowCount(0);
        for (Service s : services) {
            if (s.getClientName().equals(searchText.getText())) {
                fillRow(s);
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void displayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {

        System.out.print("hola");

        if (displayComboBox.getSelectedItem().equals("General")) {
            hideSearch();
            displayServices();
        } else if (displayComboBox.getSelectedItem().equals("Búsqueda Personalizada")) {
            showSearch();
        }
    }

    public void hideSearch() {
        searchText.setVisible(false);
        searchButton.setVisible(false);
    }

    public void showSearch() {
        searchText.setVisible(true);
        searchButton.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MHLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgdLabel;
    private javax.swing.JComboBox<String> displayComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JSeparator separator;
    private javax.swing.JScrollPane servicesSP;
    private javax.swing.JTable servicesTable;
    // End of variables declaration//GEN-END:variables
}
